import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./style.css";
import SignOutButton from '@/components/buttons/SignOutButton';
import { createClient } from '@/util/supabase/server';
import AuthButtons from '@/components/layout/header/AuthButtons';
import DashboardLink from '@/components/layout/header/DashboardLink';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();

  const loggedIn = !!user;

  return (
    <html lang="en">
      <head>
        <meta name="google-signin-client_id" content="961657177961-62qmq2ojrg0quor18spps69iktv2pvp9.apps.googleusercontent.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <header className='flex h-[100px] px-5 border-b border-neutral-800 items-center leading-none justify-between'>
          <h1 className='text-xl'><Link href='/'>Gitnalytics</Link></h1>
          <div className='w-fit flex gap-4 items-center'>
            {loggedIn ? <SignOutButton /> : null}
            {!loggedIn ? 
              <AuthButtons/>
            : <DashboardLink/>}
          </div>
        </header>
        <main className='flex flex-col flex-grow'>

          {children}
        </main>
      </body>
    </html>
  );
}
